apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: timelineserver
  namespace: xiaobailong
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: yarn
        k8s-app: timelineserver
    spec:
      containers:
        - name: timelineserver
          image: xiaobailong/hadoop_in_docker_k8s:3.0.3
          imagePullPolicy: Always
          command: ["yarn"]
          args: ["timelineserver"]
          ports:
            - containerPort: 8188
              protocol: TCP
            - containerPort: 10200
              protocol: TCP
            - containerPort: 8190
              protocol: TCP
      hostname: timelineserver
      subdomain: yarn-ts

---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: yarn
    k8s-app: timelineserver
  name: yarn-ts
  namespace: xiaobailong
spec:
  ports:
    - name: yarn-8188
      port: 8188
      targetPort: 8188
  type: NodePort
  selector:
    k8s-app: timelineserver