apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: datanode1
  namespace: ones
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: hdfs
        k8s-app: datanode1
    spec:
      containers:
        - name: datanode1
          image: xiaobailong/hadoop_in_docker_k8s:3.0.3
          imagePullPolicy: Always
          command: ["hdfs"]
          args: ["datanode","-fs", "hdfs://namenode.hdfs-nm.xiaobailong.svc.cluster.local:9000","-Ddfs.datanode.data.dir=/data/hadoop/dfs/datanode","-Ddfs.permissions.enabled=false"]
          ports:
            - containerPort: 9864
              protocol: TCP
            - containerPort: 9866
              protocol: TCP
          volumeMounts:
            - mountPath: /data/hadoop/dfs/datanode
              name: datanode1-data
      hostname: datanode1
      subdomain: hdfs-dn1
      volumes:
        - name: datanode1-data
          hostPath:
            path: /mnt/nfs/hdfs/datanode1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: hdfs
    k8s-app: datanode1
  name: hdfs-dn1
  namespace: ones
spec:
  ports:
    - name: hdfs-9864
      port: 9864
      targetPort: 9864
    - name: hdfs-9866
      port: 9866
      targetPort: 9866
  type: ClusterIP
  selector:
    k8s-app: datanode1